webtalk_init -webtalk_dir C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.sim/sim_1/behav/xsim/xsim.dir/TB_CLK_SAFE_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 26 17:26:33 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174111626_180558066_210613388_046" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "25a0974f-0ff1-4731-91f0-b8e3356292c6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "21e58bb949f44e2cb611c0d8fba278d7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "10" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14616_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2277355229 -regid "174111626_180558066_210613388_046" -xml C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.sim/sim_1/behav/xsim/xsim.dir/TB_CLK_SAFE_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.sim/sim_1/behav/xsim/xsim.dir/TB_CLK_SAFE_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.sim/sim_1/behav/xsim/xsim.dir/TB_CLK_SAFE_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
