# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z014sclg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.cache/wt [current_project]
set_property parent.project_path C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part infn.it:mpmt:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/ip_repo/myip2_1.0
  c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/ip_repo/myip_1.0
  c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/ip_repo/RunControl_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set src_rc [catch { 
  puts "source C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/utils_1/imports/Downloads/revision.tcl"
  source C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/utils_1/imports/Downloads/revision.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 error "$_RESULT"
  send_msg_id runtcl-2 error "sourcing script C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/utils_1/imports/Downloads/revision.tcl failed"
  return -code error
}
read_vhdl -library xil_defaultlib {
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/pippopakage.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/CLK_SAFE.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/Canale_secondi.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/remote_sources/_/SPI_1ch.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/remote_sources/_/OSC_240MHZ.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/remote_sources/_/ENERGY_1ch.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/remote_sources/_/FF_FE.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/remote_sources/_/FF_RE.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/remote_sources/_/ROM_DECODE.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/remote_sources/_/FLIP_FLOP_MASTER.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/Pulser.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/RESET_MODULE.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/new/RunControl_AXI.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/remote_sources/_/canale_tempo.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/remote_sources/_/single_channel.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/raccolta_dati.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/raccolta_canali.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/Main_V0_Fir_V_2_2/pps_module2.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/imports/hdl/TOP_block_wrapper.vhd
  C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/new/TOP.vhd
}
add_files C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/TOP_block.bd
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_xbar_0/TOP_block_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_axi_uartlite_1_0/TOP_block_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_axi_uartlite_1_0/TOP_block_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_axi_uartlite_1_0/TOP_block_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_axi_dma_0_0/TOP_block_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_axi_dma_0_0/TOP_block_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_axi_dma_0_0/TOP_block_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_axis_data_fifo_0_1/TOP_block_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_xbar_1/TOP_block_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_auto_pc_0/TOP_block_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_auto_pc_1/TOP_block_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/TOP_block_ooc.xdc]

read_ip -quiet C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/constrs_1/new/TOP.xdc
set_property used_in_implementation false [get_files C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/constrs_1/new/TOP.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOP -part xc7z014sclg484-2 -retiming


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
