# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v4_UART_ACQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/FIFO_DATA/FIFO_DATA.xci
# IP: The module: 'FIFO_DATA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v4_UART_ACQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/FIFO_DATA/FIFO_DATA.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_DATA'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v4_UART_ACQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/FIFO_DATA/FIFO_DATA_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_DATA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v4_UART_ACQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/FIFO_DATA/FIFO_DATA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_DATA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v4_UART_ACQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/FIFO_DATA/FIFO_DATA.xci
# IP: The module: 'FIFO_DATA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v4_UART_ACQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/FIFO_DATA/FIFO_DATA.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_DATA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v4_UART_ACQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/FIFO_DATA/FIFO_DATA_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_DATA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ _v4_UART_ACQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/ip/FIFO_DATA/FIFO_DATA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_DATA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
