# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0.xci
# IP: The module: 'TOP_block_rst_ps7_0_200M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0.xci
# IP: The module: 'TOP_block_rst_ps7_0_200M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SER/Desktop/T2K/mPMT/MAIN_ACQ_ZYNQ/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_rst_ps7_0_200M_0/TOP_block_rst_ps7_0_200M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_rst_ps7_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
