##Bank 13 VCC0=3V3
##Bank 33 VCC0=3V3
##Bank 34 VCC0=3V3
##Bank 35 VCC0=2V5


## Clock signal
#Bank = 35, Pin name = IO_L14P_T2_AD4P_SRCC,					Sch name = 25MHZ
set_property PACKAGE_PIN D20 [get_ports CLK_25MHZ]
set_property IOSTANDARD LVCMOS25 [get_ports CLK_25MHZ]
create_clock -period 40.000 -name CLK_25MHZ -waveform {0.000 20.000} -add [get_ports CLK_25MHZ]

#EXT_CLOCK CAVO
set_property IOSTANDARD LVDS_25 [get_ports REF_CLK_P]
set_property DIFF_TERM TRUE [get_ports REF_CLK_P]
set_property PACKAGE_PIN B19 [get_ports REF_CLK_P]
set_property PACKAGE_PIN B20 [get_ports REF_CLK_N]
set_property IOSTANDARD LVDS_25 [get_ports REF_CLK_N]
set_property DIFF_TERM TRUE [get_ports REF_CLK_N]

set_property IOSTANDARD LVDS_25 [get_ports REF_CLK2_P]
set_property DIFF_TERM TRUE [get_ports REF_CLK2_P]
set_property PACKAGE_PIN D18 [get_ports REF_CLK2_P]
set_property PACKAGE_PIN C19 [get_ports REF_CLK2_N]
set_property IOSTANDARD LVDS_25 [get_ports REF_CLK2_N]
set_property DIFF_TERM TRUE [get_ports REF_CLK2_N]

create_clock -period 40.000 -name REF_CLK_P -waveform {0.000 20.000} -add [get_ports REF_CLK_P]
create_clock -period 40.000 -name REF_CLK2_P -waveform {0.000 20.000} -add [get_ports REF_CLK2_P]



##TRIGGER  BANK 35 VCC_2V5 STD LVDS_25
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[0]}]
set_property PACKAGE_PIN E15 [get_ports {OUT_TIME_P[0]}]
set_property PACKAGE_PIN D15 [get_ports {OUT_TIME_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[0]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[0]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[0]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[1]}]
set_property PACKAGE_PIN G15 [get_ports {OUT_TIME_P[1]}]
set_property PACKAGE_PIN G16 [get_ports {OUT_TIME_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[1]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[1]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[1]}]


set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[2]}]
set_property PACKAGE_PIN A16 [get_ports {OUT_TIME_P[2]}]
set_property PACKAGE_PIN A17 [get_ports {OUT_TIME_N[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[2]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[2]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[2]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[3]}]
set_property PACKAGE_PIN F18 [get_ports {OUT_TIME_P[3]}]
set_property PACKAGE_PIN E18 [get_ports {OUT_TIME_N[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[3]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[3]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[3]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[4]}]
set_property PACKAGE_PIN F21 [get_ports {OUT_TIME_P[4]}]
set_property PACKAGE_PIN F22 [get_ports {OUT_TIME_N[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[4]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[4]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[4]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[5]}]
set_property PACKAGE_PIN H19 [get_ports {OUT_TIME_P[5]}]
set_property PACKAGE_PIN H20 [get_ports {OUT_TIME_N[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[5]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[5]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[5]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[6]}]
set_property PACKAGE_PIN G19 [get_ports {OUT_TIME_P[6]}]
set_property PACKAGE_PIN F19 [get_ports {OUT_TIME_N[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[6]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[6]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[6]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[7]}]
set_property PACKAGE_PIN G17 [get_ports {OUT_TIME_P[7]}]
set_property PACKAGE_PIN F17 [get_ports {OUT_TIME_N[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[7]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[7]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[7]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[8]}]
set_property PACKAGE_PIN G20 [get_ports {OUT_TIME_P[8]}]
set_property PACKAGE_PIN G21 [get_ports {OUT_TIME_N[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[8]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[8]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[8]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[9]}]
set_property PACKAGE_PIN B21 [get_ports {OUT_TIME_P[9]}]
set_property PACKAGE_PIN B22 [get_ports {OUT_TIME_N[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[9]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[9]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[9]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[10]}]
set_property PACKAGE_PIN A18 [get_ports {OUT_TIME_P[10]}]
set_property PACKAGE_PIN A19 [get_ports {OUT_TIME_N[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[10]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[10]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[10]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[11]}]
set_property PACKAGE_PIN F16 [get_ports {OUT_TIME_P[11]}]
set_property PACKAGE_PIN E16 [get_ports {OUT_TIME_N[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[11]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[11]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[11]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[12]}]
set_property PACKAGE_PIN D16 [get_ports {OUT_TIME_P[12]}]
set_property PACKAGE_PIN D17 [get_ports {OUT_TIME_N[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[12]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[12]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[12]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[13]}]
set_property PACKAGE_PIN C15 [get_ports {OUT_TIME_P[13]}]
set_property PACKAGE_PIN B15 [get_ports {OUT_TIME_N[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[13]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[13]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[13]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[14]}]
set_property PACKAGE_PIN D22 [get_ports {OUT_TIME_P[14]}]
set_property PACKAGE_PIN C22 [get_ports {OUT_TIME_N[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[14]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[14]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[14]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[15]}]
set_property PACKAGE_PIN E19 [get_ports {OUT_TIME_P[15]}]
set_property PACKAGE_PIN E20 [get_ports {OUT_TIME_N[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[15]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[15]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[15]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[16]}]
set_property PACKAGE_PIN E21 [get_ports {OUT_TIME_P[16]}]
set_property PACKAGE_PIN D21 [get_ports {OUT_TIME_N[16]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[16]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[16]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[16]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[17]}]
set_property PACKAGE_PIN B16 [get_ports {OUT_TIME_P[17]}]
set_property PACKAGE_PIN B17 [get_ports {OUT_TIME_N[17]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[17]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[17]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[17]}]

set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_P[18]}]
set_property PACKAGE_PIN A21 [get_ports {OUT_TIME_P[18]}]
set_property PACKAGE_PIN A22 [get_ports {OUT_TIME_N[18]}]
set_property IOSTANDARD LVDS_25 [get_ports {OUT_TIME_N[18]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_P[18]}]
set_property DIFF_TERM TRUE [get_ports {OUT_TIME_N[18]}]

#EXT TRIGGER CAVO
set_property IOSTANDARD LVDS_25 [get_ports EXT_TRG_P]
set_property PACKAGE_PIN C17 [get_ports EXT_TRG_P]
set_property PACKAGE_PIN C18 [get_ports EXT_TRG_N]
set_property IOSTANDARD LVDS_25 [get_ports EXT_TRG_N]

set_property IOSTANDARD LVDS_25 [get_ports EXT_TRG2_P]
set_property PACKAGE_PIN H22 [get_ports EXT_TRG2_P]
set_property PACKAGE_PIN G22 [get_ports EXT_TRG2_N]
set_property IOSTANDARD LVDS_25 [get_ports EXT_TRG2_N]

##FTDI  BANK 13 VCC_3V3 STD LVCMOS33
#set_property PACKAGE_PIN U7 [get_ports {FTDI_DATA[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {FTDI_DATA[0]}]
#set_property PACKAGE_PIN AB12 [get_ports {FTDI_DATA[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {FTDI_DATA[1]}]
#set_property PACKAGE_PIN AB11 [get_ports {FTDI_DATA[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {FTDI_DATA[2]}]
#set_property PACKAGE_PIN AA11 [get_ports {FTDI_DATA[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {FTDI_DATA[3]}]
#set_property PACKAGE_PIN AB10 [get_ports {FTDI_DATA[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {FTDI_DATA[4]}]
#set_property PACKAGE_PIN AB9 [get_ports {FTDI_DATA[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {FTDI_DATA[5]}]
#set_property PACKAGE_PIN AA9 [get_ports {FTDI_DATA[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {FTDI_DATA[6]}]
#set_property PACKAGE_PIN AA8 [get_ports {FTDI_DATA[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {FTDI_DATA[7]}]
#set_property PACKAGE_PIN AB2 [get_ports FTDI_SIWU]
#set_property IOSTANDARD LVCMOS33 [get_ports FTDI_SIWU]
#set_property PACKAGE_PIN AB4 [get_ports FTDI_WR]
#set_property IOSTANDARD LVCMOS33 [get_ports FTDI_WR]
#set_property PACKAGE_PIN AB5 [get_ports FTDI_RDn]
#set_property IOSTANDARD LVCMOS33 [get_ports FTDI_RDn]
#set_property PACKAGE_PIN AB6 [get_ports FTDI_TXE]
#set_property IOSTANDARD LVCMOS33 [get_ports FTDI_TXE]
#set_property PACKAGE_PIN AB7 [get_ports FTDI_RXFn]
#set_property IOSTANDARD LVCMOS33 [get_ports FTDI_RXFn]
#set_property PACKAGE_PIN Y4 [get_ports FTDI_OEn]
#set_property IOSTANDARD LVCMOS33 [get_ports FTDI_OEn]
#set_property PACKAGE_PIN Y5 [get_ports FTDI_CLK]
#set_property IOSTANDARD LVCMOS33 [get_ports FTDI_CLK]
#create_clock -period 16.667 -name FTDI_CLK -waveform {0.000 8.333} -add [get_ports FTDI_CLK]

#UART TX e RXn
#TX
set_property PACKAGE_PIN U12 [get_ports TX_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports TX_OUT]
#RX
set_property PACKAGE_PIN R20 [get_ports {RX_IN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[0]}]
set_property PACKAGE_PIN R18 [get_ports {RX_IN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[1]}]
set_property PACKAGE_PIN P16 [get_ports {RX_IN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[2]}]
set_property PACKAGE_PIN V9 [get_ports {RX_IN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[3]}]
set_property PACKAGE_PIN W11 [get_ports {RX_IN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[4]}]
set_property PACKAGE_PIN Y10 [get_ports {RX_IN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[5]}]
set_property PACKAGE_PIN Y13 [get_ports {RX_IN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[6]}]
set_property PACKAGE_PIN AA14 [get_ports {RX_IN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[7]}]
set_property PACKAGE_PIN AB17 [get_ports {RX_IN[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[8]}]
set_property PACKAGE_PIN W22 [get_ports {RX_IN[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[9]}]
set_property PACKAGE_PIN T21 [get_ports {RX_IN[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[10]}]
set_property PACKAGE_PIN H15 [get_ports {RX_IN[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[11]}]
set_property PACKAGE_PIN P18 [get_ports {RX_IN[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[12]}]
set_property PACKAGE_PIN V19 [get_ports {RX_IN[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[13]}]
set_property PACKAGE_PIN Y8 [get_ports {RX_IN[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[14]}]
set_property PACKAGE_PIN V7 [get_ports {RX_IN[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[15]}]
set_property PACKAGE_PIN AA17 [get_ports {RX_IN[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[16]}]
set_property PACKAGE_PIN J15 [get_ports {RX_IN[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[17]}]
set_property PACKAGE_PIN V20 [get_ports {RX_IN[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_IN[18]}]

##ADC SCL, SDA, CS
#SCL
set_property PACKAGE_PIN N22 [get_ports {ADC_SCL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[0]}]
set_property PACKAGE_PIN N18 [get_ports {ADC_SCL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[1]}]
set_property PACKAGE_PIN U15 [get_ports {ADC_SCL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[2]}]
set_property PACKAGE_PIN M15 [get_ports {ADC_SCL[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[3]}]
set_property PACKAGE_PIN W12 [get_ports {ADC_SCL[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[4]}]
set_property PACKAGE_PIN W8 [get_ports {ADC_SCL[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[5]}]
set_property PACKAGE_PIN Y14 [get_ports {ADC_SCL[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[6]}]
set_property PACKAGE_PIN AB14 [get_ports {ADC_SCL[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[7]}]
set_property PACKAGE_PIN AA16 [get_ports {ADC_SCL[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[8]}]
set_property PACKAGE_PIN U21 [get_ports {ADC_SCL[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[9]}]
set_property PACKAGE_PIN R21 [get_ports {ADC_SCL[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[10]}]
set_property PACKAGE_PIN J21 [get_ports {ADC_SCL[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[11]}]
set_property PACKAGE_PIN N17 [get_ports {ADC_SCL[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[12]}]
set_property PACKAGE_PIN U19 [get_ports {ADC_SCL[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[13]}]
set_property PACKAGE_PIN Y16 [get_ports {ADC_SCL[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[14]}]
set_property PACKAGE_PIN Y19 [get_ports {ADC_SCL[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[15]}]
set_property PACKAGE_PIN AA19 [get_ports {ADC_SCL[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[16]}]
set_property PACKAGE_PIN L21 [get_ports {ADC_SCL[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[17]}]
set_property PACKAGE_PIN AA21 [get_ports {ADC_SCL[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SCL[18]}]

#ADC_CS
set_property PACKAGE_PIN P22 [get_ports {ADC_CS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[0]}]
set_property PACKAGE_PIN N19 [get_ports {ADC_CS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[1]}]
set_property PACKAGE_PIN V15 [get_ports {ADC_CS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[2]}]
set_property PACKAGE_PIN V10 [get_ports {ADC_CS[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[3]}]
set_property PACKAGE_PIN V12 [get_ports {ADC_CS[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[4]}]
set_property PACKAGE_PIN AA7 [get_ports {ADC_CS[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[5]}]
set_property PACKAGE_PIN V14 [get_ports {ADC_CS[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[6]}]
set_property PACKAGE_PIN AA13 [get_ports {ADC_CS[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[7]}]
set_property PACKAGE_PIN AB16 [get_ports {ADC_CS[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[8]}]
set_property PACKAGE_PIN V22 [get_ports {ADC_CS[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[9]}]
set_property PACKAGE_PIN T22 [get_ports {ADC_CS[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[10]}]
set_property PACKAGE_PIN K21 [get_ports {ADC_CS[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[11]}]
set_property PACKAGE_PIN P17 [get_ports {ADC_CS[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[12]}]
set_property PACKAGE_PIN U20 [get_ports {ADC_CS[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[13]}]
set_property PACKAGE_PIN Y15 [get_ports {ADC_CS[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[14]}]
set_property PACKAGE_PIN W18 [get_ports {ADC_CS[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[15]}]
set_property PACKAGE_PIN AA18 [get_ports {ADC_CS[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[16]}]
set_property PACKAGE_PIN M22 [get_ports {ADC_CS[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[17]}]
set_property PACKAGE_PIN AB22 [get_ports {ADC_CS[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_CS[18]}]

#SDATA
set_property PACKAGE_PIN M21 [get_ports {ADC_SDATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[0]}]
set_property PACKAGE_PIN M20 [get_ports {ADC_SDATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[1]}]
set_property PACKAGE_PIN V17 [get_ports {ADC_SDATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[2]}]
set_property PACKAGE_PIN N15 [get_ports {ADC_SDATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[3]}]
set_property PACKAGE_PIN W13 [get_ports {ADC_SDATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[4]}]
set_property PACKAGE_PIN V13 [get_ports {ADC_SDATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[5]}]
set_property PACKAGE_PIN W15 [get_ports {ADC_SDATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[6]}]
set_property PACKAGE_PIN AA12 [get_ports {ADC_SDATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[7]}]
set_property PACKAGE_PIN AB15 [get_ports {ADC_SDATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[8]}]
set_property PACKAGE_PIN U22 [get_ports {ADC_SDATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[9]}]
set_property PACKAGE_PIN P21 [get_ports {ADC_SDATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[10]}]
set_property PACKAGE_PIN J22 [get_ports {ADC_SDATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[11]}]
set_property PACKAGE_PIN M19 [get_ports {ADC_SDATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[12]}]
set_property PACKAGE_PIN T19 [get_ports {ADC_SDATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[13]}]
set_property PACKAGE_PIN W16 [get_ports {ADC_SDATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[14]}]
set_property PACKAGE_PIN Y18 [get_ports {ADC_SDATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[15]}]
set_property PACKAGE_PIN AB19 [get_ports {ADC_SDATA[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[16]}]
set_property PACKAGE_PIN L22 [get_ports {ADC_SDATA[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[17]}]
set_property PACKAGE_PIN AA22 [get_ports {ADC_SDATA[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_SDATA[18]}]

#OverCurrent e PowerEnable

#PowerEnable
set_property PACKAGE_PIN K16 [get_ports {PWR_EN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[0]}]
set_property PACKAGE_PIN K20 [get_ports {PWR_EN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[1]}]
set_property PACKAGE_PIN R16 [get_ports {PWR_EN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[2]}]
set_property PACKAGE_PIN Y21 [get_ports {PWR_EN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[3]}]
set_property PACKAGE_PIN R15 [get_ports {PWR_EN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[4]}]
set_property PACKAGE_PIN AA6 [get_ports {PWR_EN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[5]}]
set_property PACKAGE_PIN T18 [get_ports {PWR_EN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[6]}]
set_property PACKAGE_PIN N20 [get_ports {PWR_EN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[7]}]
set_property PACKAGE_PIN R19 [get_ports {PWR_EN[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[8]}]
set_property PACKAGE_PIN AB20 [get_ports {PWR_EN[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[9]}]
set_property PACKAGE_PIN K15 [get_ports {PWR_EN[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[10]}]
set_property PACKAGE_PIN J16 [get_ports {PWR_EN[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[11]}]
set_property PACKAGE_PIN U16 [get_ports {PWR_EN[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[12]}]
set_property PACKAGE_PIN K18 [get_ports {PWR_EN[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[13]}]
set_property PACKAGE_PIN Y11 [get_ports {PWR_EN[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[14]}]
set_property PACKAGE_PIN Y9 [get_ports {PWR_EN[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[15]}]
set_property PACKAGE_PIN AB21 [get_ports {PWR_EN[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[16]}]
set_property PACKAGE_PIN L16 [get_ports {PWR_EN[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[17]}]
set_property PACKAGE_PIN W21 [get_ports {PWR_EN[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[18]}]

#OverCurrent
set_property PACKAGE_PIN J17 [get_ports {OVC_CH[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[0]}]
set_property PACKAGE_PIN M17 [get_ports {OVC_CH[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[1]}]
set_property PACKAGE_PIN V18 [get_ports {OVC_CH[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[2]}]
set_property PACKAGE_PIN W20 [get_ports {OVC_CH[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[3]}]
set_property PACKAGE_PIN U14 [get_ports {OVC_CH[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[4]}]
set_property PACKAGE_PIN P15 [get_ports {OVC_CH[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[5]}]
set_property PACKAGE_PIN T17 [get_ports {OVC_CH[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[6]}]
set_property PACKAGE_PIN P20 [get_ports {OVC_CH[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[7]}]
set_property PACKAGE_PIN T16 [get_ports {OVC_CH[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[8]}]
set_property PACKAGE_PIN W7 [get_ports {OVC_CH[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[9]}]
set_property PACKAGE_PIN J18 [get_ports {OVC_CH[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[10]}]
set_property PACKAGE_PIN J20 [get_ports {OVC_CH[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[11]}]
set_property PACKAGE_PIN U17 [get_ports {OVC_CH[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[12]}]
set_property PACKAGE_PIN L17 [get_ports {OVC_CH[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[13]}]
set_property PACKAGE_PIN W10 [get_ports {OVC_CH[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[14]}]
set_property PACKAGE_PIN V8 [get_ports {OVC_CH[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[15]}]
set_property PACKAGE_PIN W17 [get_ports {OVC_CH[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[16]}]
set_property PACKAGE_PIN M16 [get_ports {OVC_CH[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[17]}]
set_property PACKAGE_PIN Y20 [get_ports {OVC_CH[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OVC_CH[18]}]


### CALIB
set_property PACKAGE_PIN T6 [get_ports CLK_25_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_25_OUT]
#set_property PACKAGE_PIN R6 [get_ports {CALIB[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {CALIB[1]}]
#set_property PACKAGE_PIN U11 [get_ports {CALIB[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {CALIB[2]}]
#set_property PACKAGE_PIN R7 [get_ports {CALIB[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {CALIB[3]}]
#set_property PACKAGE_PIN U6 [get_ports {CALIB[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {CALIB[4]}]
#set_property PACKAGE_PIN U9 [get_ports {CALIB[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {CALIB[5]}]
#set_property PACKAGE_PIN U10 [get_ports {CALIB[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {CALIB[6]}]
#set_property PACKAGE_PIN P20 [get_ports {CALIB[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {CALIB[7]}]


##I2C EMIO
set_property PACKAGE_PIN AB1 [get_ports I2C_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SDA]
set_property PACKAGE_PIN T4 [get_ports I2C_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SCL]
set_property PULLUP true [get_ports I2C_SDA]
set_property PULLUP true [get_ports I2C_SCL]


##SAMA5D27 connections
#set_property PACKAGE_PIN U4 [get_ports Reset_IN]
#set_property IOSTANDARD LVCMOS33 [get_ports Reset_IN]
##UART slow control
#set_property PACKAGE_PIN AA4 [get_ports RX_SlowControl]
#set_property IOSTANDARD LVCMOS33 [get_ports RX_SlowControl]
#set_property PACKAGE_PIN V4 [get_ports TX_SlowControl]
#set_property IOSTANDARD LVCMOS33 [get_ports TX_SlowControl]
##uart run control
#set_property PACKAGE_PIN V5 [get_ports RX_RunControl]
#set_property IOSTANDARD LVCMOS33 [get_ports RX_RunControl]
#set_property PACKAGE_PIN Y6 [get_ports TX_RunControl]
#set_property IOSTANDARD LVCMOS33 [get_ports TX_RunControl]
#uart boot sama to zynq EMIO
set_property PACKAGE_PIN W6 [get_ports SAMA_RX]
set_property IOSTANDARD LVCMOS33 [get_ports SAMA_RX]
set_property PACKAGE_PIN U5 [get_ports SAMA_TX]
set_property IOSTANDARD LVCMOS33 [get_ports SAMA_TX]

##JTAG
#set_property PACKAGE_PIN W5 [get_ports SAMA_TDO]
#set_property IOSTANDARD LVCMOS33 [get_ports SAMA_TDO]
#set_property PACKAGE_PIN L18 [get_ports SAMA_TDI]
#set_property IOSTANDARD LVCMOS33 [get_ports SAMA_TDI]
#set_property PACKAGE_PIN L19 [get_ports SAMA_TCK]
#set_property IOSTANDARD LVCMOS33 [get_ports SAMA_TCK]
#set_property PACKAGE_PIN K19 [get_ports SAMA_TMS]
#set_property IOSTANDARD LVCMOS33 [get_ports SAMA_TMS]

set_switching_activity -toggle_rate 5.000 -type {register} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {io_output} -static_probability 0.050 -all 



set_property LOAD 100 [get_ports {ADC_CS[0]}]
set_property LOAD 100 [get_ports {ADC_CS[10]}]
set_property LOAD 100 [get_ports {ADC_CS[11]}]
set_property LOAD 100 [get_ports {ADC_CS[12]}]
set_property LOAD 100 [get_ports {ADC_CS[13]}]
set_property LOAD 100 [get_ports {ADC_CS[14]}]
set_property LOAD 100 [get_ports {ADC_CS[15]}]
set_property LOAD 100 [get_ports {ADC_CS[16]}]
set_property LOAD 100 [get_ports {ADC_CS[17]}]
set_property LOAD 100 [get_ports {ADC_CS[18]}]
set_property LOAD 100 [get_ports {ADC_CS[1]}]
set_property LOAD 100 [get_ports {ADC_CS[2]}]
set_property LOAD 100 [get_ports {ADC_CS[3]}]
set_property LOAD 100 [get_ports {ADC_CS[4]}]
set_property LOAD 100 [get_ports {ADC_CS[5]}]
set_property LOAD 100 [get_ports {ADC_CS[6]}]
set_property LOAD 100 [get_ports {ADC_CS[7]}]
set_property LOAD 100 [get_ports {ADC_CS[8]}]
set_property LOAD 100 [get_ports {ADC_CS[9]}]
set_property LOAD 100 [get_ports {ADC_SCL[0]}]
set_property LOAD 100 [get_ports {ADC_SCL[10]}]
set_property LOAD 100 [get_ports {ADC_SCL[11]}]
set_property LOAD 100 [get_ports {ADC_SCL[12]}]
set_property LOAD 100 [get_ports {ADC_SCL[13]}]
set_property LOAD 100 [get_ports {ADC_SCL[14]}]
set_property LOAD 100 [get_ports {ADC_SCL[15]}]
set_property LOAD 100 [get_ports {ADC_SCL[16]}]
set_property LOAD 100 [get_ports {ADC_SCL[17]}]
set_property LOAD 100 [get_ports {ADC_SCL[18]}]
set_property LOAD 100 [get_ports {ADC_SCL[1]}]
set_property LOAD 100 [get_ports {ADC_SCL[2]}]
set_property LOAD 100 [get_ports {ADC_SCL[3]}]
set_property LOAD 100 [get_ports {ADC_SCL[4]}]
set_property LOAD 100 [get_ports {ADC_SCL[5]}]
set_property LOAD 100 [get_ports {ADC_SCL[6]}]
set_property LOAD 100 [get_ports {ADC_SCL[7]}]
set_property LOAD 100 [get_ports {ADC_SCL[8]}]
set_property LOAD 100 [get_ports {ADC_SCL[9]}]
set_property LOAD 100 [get_ports {DDR_addr[0]}]
set_property LOAD 100 [get_ports {DDR_addr[10]}]
set_property LOAD 100 [get_ports {DDR_addr[11]}]
set_property LOAD 100 [get_ports {DDR_addr[12]}]
set_property LOAD 100 [get_ports {DDR_addr[13]}]
set_property LOAD 100 [get_ports {DDR_addr[14]}]
set_property LOAD 100 [get_ports {DDR_addr[1]}]
set_property LOAD 100 [get_ports {DDR_addr[2]}]
set_property LOAD 100 [get_ports {DDR_addr[3]}]
set_property LOAD 100 [get_ports {DDR_addr[4]}]
set_property LOAD 100 [get_ports {DDR_addr[5]}]
set_property LOAD 100 [get_ports {DDR_addr[6]}]
set_property LOAD 100 [get_ports {DDR_addr[7]}]
set_property LOAD 100 [get_ports {DDR_addr[8]}]
set_property LOAD 100 [get_ports {DDR_addr[9]}]
set_property LOAD 100 [get_ports {DDR_ba[0]}]
set_property LOAD 100 [get_ports {DDR_ba[1]}]
set_property LOAD 100 [get_ports {DDR_ba[2]}]
set_property LOAD 100 [get_ports DDR_cas_n]
set_property LOAD 100 [get_ports DDR_ck_n]
set_property LOAD 100 [get_ports DDR_ck_p]
set_property LOAD 100 [get_ports DDR_cke]
set_property LOAD 100 [get_ports DDR_cs_n]
set_property LOAD 100 [get_ports {DDR_dm[0]}]
set_property LOAD 100 [get_ports {DDR_dm[1]}]
set_property LOAD 100 [get_ports {DDR_dm[2]}]
set_property LOAD 100 [get_ports {DDR_dm[3]}]
set_property LOAD 100 [get_ports {DDR_dq[0]}]
set_property LOAD 100 [get_ports {DDR_dq[10]}]
set_property LOAD 100 [get_ports {DDR_dq[11]}]
set_property LOAD 100 [get_ports {DDR_dq[12]}]
set_property LOAD 100 [get_ports {DDR_dq[13]}]
set_property LOAD 100 [get_ports {DDR_dq[14]}]
set_property LOAD 100 [get_ports {DDR_dq[15]}]
set_property LOAD 100 [get_ports {DDR_dq[16]}]
set_property LOAD 100 [get_ports {DDR_dq[17]}]
set_property LOAD 100 [get_ports {DDR_dq[18]}]
set_property LOAD 100 [get_ports {DDR_dq[19]}]
set_property LOAD 100 [get_ports {DDR_dq[1]}]
set_property LOAD 100 [get_ports {DDR_dq[20]}]
set_property LOAD 100 [get_ports {DDR_dq[21]}]
set_property LOAD 100 [get_ports {DDR_dq[22]}]
set_property LOAD 100 [get_ports {DDR_dq[23]}]
set_property LOAD 100 [get_ports {DDR_dq[24]}]
set_property LOAD 100 [get_ports {DDR_dq[25]}]
set_property LOAD 100 [get_ports {DDR_dq[26]}]
set_property LOAD 100 [get_ports {DDR_dq[27]}]
set_property LOAD 100 [get_ports {DDR_dq[28]}]
set_property LOAD 100 [get_ports {DDR_dq[29]}]
set_property LOAD 100 [get_ports {DDR_dq[2]}]
set_property LOAD 100 [get_ports {DDR_dq[30]}]
set_property LOAD 100 [get_ports {DDR_dq[31]}]
set_property LOAD 100 [get_ports {DDR_dq[3]}]
set_property LOAD 100 [get_ports {DDR_dq[4]}]
set_property LOAD 100 [get_ports {DDR_dq[5]}]
set_property LOAD 100 [get_ports {DDR_dq[6]}]
set_property LOAD 100 [get_ports {DDR_dq[7]}]
set_property LOAD 100 [get_ports {DDR_dq[8]}]
set_property LOAD 100 [get_ports {DDR_dq[9]}]
set_property LOAD 100 [get_ports {DDR_dqs_n[0]}]
set_property LOAD 100 [get_ports {DDR_dqs_n[1]}]
set_property LOAD 100 [get_ports {DDR_dqs_n[2]}]
set_property LOAD 100 [get_ports {DDR_dqs_n[3]}]
set_property LOAD 100 [get_ports {DDR_dqs_p[0]}]
set_property LOAD 100 [get_ports {DDR_dqs_p[1]}]
set_property LOAD 100 [get_ports {DDR_dqs_p[2]}]
set_property LOAD 100 [get_ports {DDR_dqs_p[3]}]
set_property LOAD 100 [get_ports DDR_odt]
set_property LOAD 100 [get_ports DDR_ras_n]
set_property LOAD 100 [get_ports DDR_reset_n]
set_property LOAD 100 [get_ports DDR_we_n]
set_property LOAD 100 [get_ports FIXED_IO_ddr_vrn]
set_property LOAD 100 [get_ports FIXED_IO_ddr_vrp]
set_property LOAD 100 [get_ports {FIXED_IO_mio[0]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[10]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[11]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[12]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[13]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[14]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[15]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[16]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[17]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[18]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[19]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[1]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[20]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[21]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[22]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[23]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[24]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[25]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[26]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[27]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[28]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[29]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[2]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[30]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[31]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[32]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[33]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[34]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[35]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[36]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[37]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[38]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[39]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[3]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[40]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[41]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[42]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[43]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[44]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[45]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[46]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[47]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[48]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[49]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[4]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[50]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[51]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[52]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[53]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[5]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[6]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[7]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[8]}]
set_property LOAD 100 [get_ports {FIXED_IO_mio[9]}]
set_property LOAD 100 [get_ports FIXED_IO_ps_clk]
set_property LOAD 100 [get_ports FIXED_IO_ps_porb]
set_property LOAD 100 [get_ports FIXED_IO_ps_srstb]
set_property LOAD 100 [get_ports I2C_SCL]
set_property LOAD 100 [get_ports I2C_SDA]
set_property LOAD 100 [get_ports {PWR_EN[0]}]
set_property LOAD 100 [get_ports {PWR_EN[10]}]
set_property LOAD 100 [get_ports {PWR_EN[11]}]
set_property LOAD 100 [get_ports {PWR_EN[12]}]
set_property LOAD 100 [get_ports {PWR_EN[13]}]
set_property LOAD 100 [get_ports {PWR_EN[14]}]
set_property LOAD 100 [get_ports {PWR_EN[15]}]
set_property LOAD 100 [get_ports {PWR_EN[16]}]
set_property LOAD 100 [get_ports {PWR_EN[17]}]
set_property LOAD 100 [get_ports {PWR_EN[18]}]
set_property LOAD 100 [get_ports {PWR_EN[1]}]
set_property LOAD 100 [get_ports {PWR_EN[2]}]
set_property LOAD 100 [get_ports {PWR_EN[3]}]
set_property LOAD 100 [get_ports {PWR_EN[4]}]
set_property LOAD 100 [get_ports {PWR_EN[5]}]
set_property LOAD 100 [get_ports {PWR_EN[6]}]
set_property LOAD 100 [get_ports {PWR_EN[7]}]
set_property LOAD 100 [get_ports {PWR_EN[8]}]
set_property LOAD 100 [get_ports {PWR_EN[9]}]
set_property LOAD 100 [get_ports SAMA_TX]
set_property LOAD 100 [get_ports TX_OUT]
set_switching_activity -toggle_rate 5.000 -type {lut} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {register} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {shift_register} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {io_output} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 0.000 -static_probability 0.000 [get_nets {TOP_block_i/TOP_block_i/ps7_0_axi_periph/xbar/inst/gen_sasd.crossbar_sasd_0/addr_arbiter_inst/SR[0]}]
set_switching_activity -toggle_rate 0.000 -static_probability 0.000 [get_nets TOP_block_i/TOP_block_i/ps7_0_axi_periph/s00_couplers/auto_pc/inst/gen_axilite.gen_b2s_conv.axilite_b2s/areset_d1]
set_switching_activity -toggle_rate 0.000 -static_probability 0.000 [get_nets {TOP_block_i/TOP_block_i/ps7_0_axi_periph/s00_couplers/auto_pc/inst/gen_axilite.gen_b2s_conv.axilite_b2s/WR.b_channel_0/bid_fifo_0/SR[0]}]
set_switching_activity -toggle_rate 0.000 -static_probability 0.000 [get_nets TOP_block_i/TOP_block_i/rst_ps7_0_200M/U0/SEQ/SEQ_COUNTER/clear]
set_switching_activity -toggle_rate 0.000 -static_probability 0.000 [get_nets {TOP_block_i/TOP_block_i/ps7_0_axi_periph/s00_couplers/auto_pc/inst/gen_axilite.gen_b2s_conv.axilite_b2s/RD.ar_channel_0/ar_cmd_fsm_0/FSM_sequential_state_reg[1]_0}]
set_switching_activity -toggle_rate 0.000 -static_probability 0.000 [get_nets TOP_block_i/TOP_block_i/ps7_0_axi_periph/s00_couplers/auto_pc/inst/gen_axilite.gen_b2s_conv.axilite_b2s/WR.aw_channel_0/aw_cmd_fsm_0/m_valid_i_reg]
set_switching_activity -toggle_rate 0.000 -static_probability 0.000 [get_nets {TOP_block_i/TOP_block_i/ps7_0_axi_periph/s00_couplers/auto_pc/inst/gen_axilite.gen_b2s_conv.axilite_b2s/SI_REG/ar.ar_pipe/aresetn_d_reg[1]_inv_0}]
set_switching_activity -toggle_rate 0.000 -static_probability 0.000 [get_nets {TOP_block_i/TOP_block_i/ps7_0_axi_periph/s00_couplers/auto_pc/inst/gen_axilite.gen_b2s_conv.axilite_b2s/SI_REG/aw.aw_pipe/aresetn_d_reg[0]_0}]
set_switching_activity -toggle_rate 0.000 -static_probability 0.000 [get_nets TOP_block_i/TOP_block_i/rst_ps7_0_200M/U0/EXT_LPF/lpf_int]

set_switching_activity -toggle_rate 5.000 -type {lut} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {register} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {shift_register} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {io_output} -static_probability 0.050 -all 

set_clock_groups -name CLK_ASYNC -asynchronous -group [get_clocks [list clk_fpga_0 CLK_25MHZ REF_CLK2_P REF_CLK_P [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT0]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT1]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT2]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT3]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT4]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT5]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT6]]]] -group [get_clocks [list clk_fpga_0 CLK_25MHZ REF_CLK2_P REF_CLK_P [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT0]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT1]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT2]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT3]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT4]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT5]] [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT6]]]]


set_property PULLUP true [get_ports {RX_IN[0]}]
set_property PULLUP true [get_ports {RX_IN[1]}]
set_property PULLUP true [get_ports {RX_IN[2]}]
set_property PULLUP true [get_ports {RX_IN[3]}]
set_property PULLUP true [get_ports {RX_IN[4]}]
set_property PULLUP true [get_ports {RX_IN[5]}]
set_property PULLUP true [get_ports {RX_IN[6]}]
set_property PULLUP true [get_ports {RX_IN[7]}]
set_property PULLUP true [get_ports {RX_IN[8]}]
set_property PULLUP true [get_ports {RX_IN[9]}]
set_property PULLUP true [get_ports {RX_IN[10]}]
set_property PULLUP true [get_ports {RX_IN[11]}]
set_property PULLUP true [get_ports {RX_IN[12]}]
set_property PULLUP true [get_ports {RX_IN[13]}]
set_property PULLUP true [get_ports {RX_IN[14]}]
set_property PULLUP true [get_ports {RX_IN[15]}]
set_property PULLUP true [get_ports {RX_IN[16]}]
set_property PULLUP true [get_ports {RX_IN[17]}]
set_property PULLUP true [get_ports {RX_IN[18]}]







set_false_path -from [get_clocks clk_fpga_2] -to [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -reset_path -from [get_clocks clk_fpga_2] -to [get_clocks -of_objects [get_pins multiphase_clock/inst/mmcm_adv_inst/CLKOUT0]]

set_operating_conditions -grade extended
set_switching_activity -toggle_rate 5.000 -type {lut} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {register} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {shift_register} -static_probability 0.050 -all 
set_switching_activity -toggle_rate 5.000 -type {io_output} -static_probability 0.050 -all 
set_multicycle_path -from [get_clocks CLK_25MHZ] -to [get_clocks clk_fpga_2] 2

set_false_path -from [get_clocks CLK_25MHZ] -to [get_clocks clk_fpga_2]


set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[17].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[4].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[0].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[16].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[3].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[1].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[10].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[14].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[6].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[2].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]

set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[13].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[15].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[18].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[11].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[8].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[12].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[9].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]
set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[5].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]

set_false_path -setup -from [get_pins Inst_Pulser/PULSER_OUT_reg/C] -to [get_pins {inst_MULTYCHANNEL/pp1[7].Inst_single_channel/Inst_blocco_time/Inst_flip_flop_time/p1[0].Inst_ff_interno_fe/o_digital_reg/D}]



create_pblock pblock_axi_dma_0
create_pblock pblock_axi_dma_0_1
add_cells_to_pblock [get_pblocks pblock_axi_dma_0_1] [get_cells -quiet [list TOP_block_i/TOP_block_i/axi_dma_0]]
resize_pblock [get_pblocks pblock_axi_dma_0_1] -add {SLICE_X26Y50:SLICE_X49Y99}
resize_pblock [get_pblocks pblock_axi_dma_0_1] -add {DSP48_X2Y20:DSP48_X2Y39}
resize_pblock [get_pblocks pblock_axi_dma_0_1] -add {RAMB18_X2Y20:RAMB18_X2Y39}
resize_pblock [get_pblocks pblock_axi_dma_0_1] -add {RAMB36_X2Y10:RAMB36_X2Y19}
