# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/LAVORO/Istituto Nazionale di Fisica Nucleare/Alfonso Boiano - T2K/Xilinx/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_xbar_0/TOP_block_xbar_0.xci
# IP: The module: 'TOP_block_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LAVORO/Istituto Nazionale di Fisica Nucleare/Alfonso Boiano - T2K/Xilinx/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_xbar_0/TOP_block_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/LAVORO/Istituto Nazionale di Fisica Nucleare/Alfonso Boiano - T2K/Xilinx/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_xbar_0/TOP_block_xbar_0.xci
# IP: The module: 'TOP_block_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LAVORO/Istituto Nazionale di Fisica Nucleare/Alfonso Boiano - T2K/Xilinx/mPMT/MAIN_ACQ-DEVEL/MAIN_ACQ_ZYNQ_v6_BUG_fixing/MAIN_ACQ/MAIN_ACQ.srcs/sources_1/bd/TOP_block/ip/TOP_block_xbar_0/TOP_block_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_block_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
